karimeSalomon/cucumber_course

Henry/print_practice_rb.rb
Henry/print_put.rb
Henry/print_puts_results.txt

Adding both files rb and results.

Print practice

---

Oscar/print_practice_rb.rb
Oscar/print_puts_result.txt

Created file for print and put in ruby

---

Emily/print_and_puts.rb
Emily/print_and_puts_result.txt

Practice print and puts

---

Alex/print_practice_rb.rb
Alex/puts_result.txt

Code and output result for the Practice 1

---

Walter/Test Fork Rubi.js
Walter/numb_and_math.rb
Walter/printvsput.rb

Day 3: Practices with operators & variables

Day 3: Practices with operators & variables

---

Emily/operators.rb

* math operators
* number/string variables

Practice: variables and operators

---

Eynar/Class2/Example.rb
Eynar/Class3/Example1.rb
Eynar/Class3/Example2.rb
Eynar/Class3/Example3.rb
Eynar/Class3/Example4.rb
Eynar/Example.rb

<Scripts-Class 3> practice variables, errors, assignation var.

---

Alex/lab2/operations.rb
Alex/lab2/operations2.rb
Alex/lab2/operations3.rb

File 1: Operators
File 2: Fibonacci
File 3: Time convertion

Class 3, files about fibonnaci and time convertion

---

Oscar/practice3.rb
Oscar/practice_3_functions.rb

Code of the usage of conversions and functions

---

Alex/lab3/class.rb
Alex/lab3/input.rb

Laboratory 3

---

Eynar/Class4/Example1.rb
Eynar/Class4/Example2.rb
Eynar/Class4/Example3.rb
Eynar/Class4/Practice1.rb

The example and practice, we made in classes.

Class 4 - methods

---

Alex/lab4/module_practice.rb

Practice about the use of modules in Ruby

---

Oscar/practice4.rb
Oscar/practice_4_modules.rb
Oscar/practice_4_require.rb

Please merge my code of 08052015

Adding files that contains code of modules and mixin

---

Eynar/Class5/Example2.rb
Eynar/Class5/Practice1.rb
Eynar/Class5/Practice1Part2.rb
Eynar/Class6/Example1Circle.rb
Eynar/Class6/Example2LocalVar.rb
Eynar/Class6/Example3InstanceVar.rb
Eynar/Class6/Example4GlobalVar.rb
Eynar/Class6/Example5ClassVar.rb
Eynar/Class6/Practice1Inheritance.rb
Eynar/Class7/Example1GetAndSet.rb
Eynar/Class7/Example2AttrReader.rb
Eynar/Class7/Example3AttrWriter.rb
Eynar/Class7/Example4AtrrAccesor.rb
Eynar/Class7/Example5Arrays.rb
Eynar/Class7/Practice1Arrays.rb

I updated the practice of modules
I added the practice for class 6

Practice Modules Updated - Practice inheritance

---

Alex/lab7/hash.rb
Alex/lab7/practice_conditionals.rb
Alex/lab7/practice_hash.rb

Practice about hash

---

Eynar/Class7/PracticePerson.rb
Eynar/Class8/Example1Hash.rb
Eynar/Class8/Practice1Hash.rb
Eynar/Class8/Practice2ControlStatements.rb

In this pull request is hash examples and the practice.

Class 8 - Hash and Practice

---

Alex/lab8/practice_iterator.rb

Practice for iterations

---

Alex/exam/first_exercise.rb

Exercise for the exam

---

Eliana/session11_cucumber/Example/features/test.feature
Eliana/session11_cucumber/output_cucumber.txt

I'm not sure if it is the expected output of execution of $cucumber fetaues/test.feature --dry-run

output_cucumber

---

Oscar/exam_1.rb
Oscar/features/session_14.feature
Oscar/features/step_definitions/session_14_steps.rb
Oscar/session_12_practice_1.feature

HI,
I commited the practices performed in classes.
Regards.

Please merge my code

---

Eynar/Cucumber/features/Example1.feature
Eynar/Cucumber/features/Example2.feature
Eynar/Cucumber/features/Example3OutLine.feature
Eynar/Cucumber/features/daily.feature
Eynar/Cucumber/features/practice.feature
Eynar/Cucumber/features/step_definitions/Parameterized_step.rb
Eynar/Cucumber/features/step_definitions/practiceStepDef.rb
Eynar/Cucumber/features/step_definitions/step1.rb
Eynar/Cucumber/features/step_definitions/step_table.rb
Eynar/Cucumber/features/step_definitions/steps_practice.rb
Eynar/Cucumber/features/support/env.rb
Eynar/Cucumber/features/support/hooks.rb
Eynar/Cucumber/features/table.feature
Eynar/Cucumber/features/test.feature
Eynar/CucumberClass/Gemfile
Eynar/CucumberClass/features/Example1.feature
Eynar/CucumberClass/features/step_definitions/step1.rb
Eynar/CucumberClass1/Gemfile.lock

I have a problems to remove item of a data table obj, this part is not working well (practice)

Examples cucumber- datatable

---

Oscar/features/FinalPractice.feature
Oscar/features/http_test.feature
Oscar/features/step_definitions/final_practice_steps.rb
Oscar/features/step_definitions/http_test_steps.rb
Oscar/features/support/config.yml
Oscar/features/support/env.rb
Oscar/features/support/helper.rb
Oscar/features/support/hooks.rb
Oscar/practice_6.rb
Oscar/practice_8_ruby_statements.rb

I will complete my practices until Tuesday 8, Sep
Thanks.
Oscar TM

Final Practice
